language: node_js
node_js:
  - "6"
notifications:
  webhooks:
    urls:
      - http://web-staging.studykik.com:9001/notifications
      - http://ec2-52-90-254-67.compute-1.amazonaws.com:9001/notifications
    on_success: always
    on_failure: never
    on_start: never

sudo: required
dist: trusty

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome.deb
 - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
 - rm google-chrome.deb
