language: node_js
node_js:
  - "5"

sudo: required
dist: trusty

before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0 
 - sh -e /etc/init.d/xvfb start
 - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome.deb
 - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
 - rm google-chrome.deb
